### ISSUE TITLE
Installation of some packages fails

### ISSUE THREAD

**Issue by raffaelepojer** [knazarov/homebrew-qemu-virgl#19]
Almost at the end returns this error

```
...
==> Applying qemu-version-v01.diff
patching file Makefile
patching file QEMU_VERSION
patching file VERSION
patching file meson.build
==> ./configure --prefix=/opt/homebrew/Cellar/qemu-virgl/20210430.1 --cc=clang --host-cc=clang --di
Last 15 lines from /Users/raffaele/Library/Logs/Homebrew/qemu-virgl/01.configure:
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program scripts/decodetree.py found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9 /private/tmp/qemu-virgl-20210503-56257-1q3f7d6/scripts/decodetree.py)
Program @INPUT@ found: NO

../target/hexagon/meson.build:33:0: ERROR: Program '@INPUT@' not found

A full log can be found at /private/tmp/qemu-virgl-20210503-56257-1q3f7d6/build/meson-logs/meson-log.txt

ERROR: meson setup failed


Do not report this issue to Homebrew/brew or Homebrew/core!
```

On MacBook Pro - M1 16GB

**Comment by knazarov** [comment]
Hi @raffaelepojer ,

Please try to apply this patch: https://github.com/knazarov/homebrew-qemu-virgl/blob/master/Patches/qemu-hexagon-v01.diff

To do that, run `brew install -d knazarov/qemu-virgl/qemu-virgl`. After it experiences the error, it will prompt you to drop to a shell. Do that. In the shell, do `patch -p1 < qemu-hexagon-v01.diff`. Then to `./configure` followed by `make` and see if the problem persists.

I haven’t yet included the patch into the master version of the formula, because I need to check that it compiles.

**Comment by Twilighttony** [comment]
Gonna be a dumb question, but where is the files located that we are supposed to patch in order for this patch to take effect? Is it in /opt/homebrew/Library/Taps ?

**Comment by knazarov** [comment]
Nevermind, I’ve already catched the problem in CI. It should be fixed in a few hours. I’ll post instructions here.

**Comment by Twilighttony** [comment]
ok so I followed your instructions. It brought me to the shell, I created the diff file with code provided above, ran the patch command and the patch succeeded, however this issue still persists.

`Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program /opt/homebrew/opt/python@3.9/bin/python3.9 found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9)
Program scripts/decodetree.py found: YES (/opt/homebrew/opt/python@3.9/bin/python3.9 /private/tmp/qemu-virgl-20210503-23376-1nq295c/scripts/decodetree.py)
Program @INPUT@ found: NO

../target/hexagon/meson.build:33:0: ERROR: Program '@INPUT@' not found

A full log can be found at /private/tmp/qemu-virgl-20210503-23376-1nq295c/build/meson-logs/meson-log.txt

ERROR: meson setup failed`

> Nevermind, I’ve already catched the problem in CI. It should be fixed in a few hours. I’ll post instructions here.

**Comment by knazarov** [comment]
Should be fixed now. Please run:

```
brew tap --force-auto-update knazarov/qemu-virgl
brew install qemu-virgl
```

**Comment by Twilighttony** [comment]
> Should be fixed now. Please run:
> 
> ```
> brew tap --force-auto-update knazarov/qemu-virgl
> brew install qemu-virgl
> ```

That worked perfectly. Thanks for such a quick fix!
